# Generated by Django 4.1.6 on 2023-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_customuser_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
